Both hour.csv and day.csv have the following fields, except hr which is not available in day.csv

- instant: record index
- dteday : date
- season : season (1:winter, 2:spring, 3:summer, 4:fall)
- yr : year (0: 2011, 1:2012)
- mnth : month ( 1 to 12)
- hr : hour (0 to 23)
- holiday : weather day is holiday or not (extracted from [Web Link])
- weekday : day of the week
- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
+ weathersit :
- 1: Clear, Few clouds, Partly cloudy, Partly cloudy
- 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
- 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
- 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp : Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)
- atemp: Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)
- hum: Normalized humidity. The values are divided to 100 (max)
- windspeed: Normalized wind speed. The values are divided to 67 (max)
- casual: count of casual users
- registered: count of registered users
- cnt: count of total rental bikes including both casual and registered

<b> Data Exploration using pandas </b>

In [1]:
import pandas as pd
import numpy as np

Task - 

- Import the dataset
- Clean, format, tranform that DF
- Grouping / Merging 
- Export the results to a file 

</b> Import the Dataset </b>

In [2]:
bikes = pd.read_csv("bike_shairing_hourly.csv")

In [3]:
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [5]:
type(bikes)

pandas.core.frame.DataFrame

In [6]:
bikes.tail()

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
17374           1           2  0.26  0.2576  0.60     0.1642      11   
17375           1           2  0.26  0.2576  0.60     0.1642       8   
17376           1           1  0.26  0.2576  0.60     0.1642       7   
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
17374         108  119  
17375          81   89  
17376          83   90  
17377          48   61  
17378          37   49

In [7]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     17379 non-null  int64  
 1   dteday      17379 non-null  object 
 2   season      17379 non-null  int64  
 3   yr          17379 non-null  int64  
 4   mnth        17379 non-null  int64  
 5   hr          17379 non-null  int64  
 6   holiday     17379 non-null  int64  
 7   weekday     17379 non-null  int64  
 8   workingday  17379 non-null  int64  
 9   weathersit  17379 non-null  int64  
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64  
 15  registered  17379 non-null  int64  
 16  cnt         17379 non-null  int64  
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


In [8]:
bikes.describe()

instant        season            yr          mnth            hr  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000   
mean    8690.0000      2.501640      0.502561      6.537775     11.546752   
std     5017.0295      1.106918      0.500008      3.438776      6.914405   
min        1.0000      1.000000      0.000000      1.000000      0.000000   
25%     4345.5000      2.000000      0.000000      4.000000      6.000000   
50%     8690.0000      3.000000      1.000000      7.000000     12.000000   
75%    13034.5000      3.000000      1.000000     10.000000     18.000000   
max    17379.0000      4.000000      1.000000     12.000000     23.000000   

            holiday       weekday    workingday    weathersit          temp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.028770      3.003683      0.682721      1.425283      0.496987   
std        0.167165      2.005771      0.465431      0.639357      0.192556   
min        0.000000      0.000000      0.000000      1.000000      0.020000   
25%        0.000000      1.000000      0.000000      1.000000      0.340000   
50%        0.000000      3.000000      1.000000      1.000000      0.500000   
75%        0.000000      5.000000      1.000000      2.000000      0.660000   
max        1.000000      6.000000      1.000000      4.000000      1.000000   

              atemp           hum     windspeed        casual    registered  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.475775      0.627229      0.190098     35.676218    153.786869   
std        0.171850      0.192930      0.122340     49.305030    151.357286   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.333300      0.480000      0.104500      4.000000     34.000000   
50%        0.484800      0.630000      0.194000     17.000000    115.000000   
75%        0.621200      0.780000      0.253700     48.000000    220.000000   
max        1.000000      1.000000      0.850700    367.000000    886.000000   

                cnt  
count  17379.000000  
mean     189.463088  
std      181.387599  
min        1.000000  
25%       40.000000  
50%      142.000000  
75%      281.000000  
max      977.000000

In [10]:
bikes.shape

(17379, 17)

In [11]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [12]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [13]:
bikes.describe()

instant        season            yr          mnth            hr  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000   
mean    8690.0000      2.501640      0.502561      6.537775     11.546752   
std     5017.0295      1.106918      0.500008      3.438776      6.914405   
min        1.0000      1.000000      0.000000      1.000000      0.000000   
25%     4345.5000      2.000000      0.000000      4.000000      6.000000   
50%     8690.0000      3.000000      1.000000      7.000000     12.000000   
75%    13034.5000      3.000000      1.000000     10.000000     18.000000   
max    17379.0000      4.000000      1.000000     12.000000     23.000000   

            holiday       weekday    workingday    weathersit          temp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.028770      3.003683      0.682721      1.425283      0.496987   
std        0.167165      2.005771      0.465431      0.639357      0.192556   
min        0.000000      0.000000      0.000000      1.000000      0.020000   
25%        0.000000      1.000000      0.000000      1.000000      0.340000   
50%        0.000000      3.000000      1.000000      1.000000      0.500000   
75%        0.000000      5.000000      1.000000      2.000000      0.660000   
max        1.000000      6.000000      1.000000      4.000000      1.000000   

              atemp           hum     windspeed        casual    registered  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.475775      0.627229      0.190098     35.676218    153.786869   
std        0.171850      0.192930      0.122340     49.305030    151.357286   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.333300      0.480000      0.104500      4.000000     34.000000   
50%        0.484800      0.630000      0.194000     17.000000    115.000000   
75%        0.621200      0.780000      0.253700     48.000000    220.000000   
max        1.000000      1.000000      0.850700    367.000000    886.000000   

                cnt  
count  17379.000000  
mean     189.463088  
std      181.387599  
min        1.000000  
25%       40.000000  
50%      142.000000  
75%      281.000000  
max      977.000000

<b> Clean , format if needed on the DF </b>

In [14]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [15]:
bikes.head(3)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32

In [16]:
bikes.instant.unique()

array([    1,     2,     3, ..., 17377, 17378, 17379], dtype=int64)

In [17]:
bikes.dteday.unique()

array(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
       '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
       '2011-01-09', '2011-01-10', '2011-01-11', '2011-01-12',
       '2011-01-13', '2011-01-14', '2011-01-15', '2011-01-16',
       '2011-01-17', '2011-01-18', '2011-01-19', '2011-01-20',
       '2011-01-21', '2011-01-22', '2011-01-23', '2011-01-24',
       '2011-01-25', '2011-01-26', '2011-01-27', '2011-01-28',
       '2011-01-29', '2011-01-30', '2011-01-31', '2011-02-01',
       '2011-02-02', '2011-02-03', '2011-02-04', '2011-02-05',
       '2011-02-06', '2011-02-07', '2011-02-08', '2011-02-09',
       '2011-02-10', '2011-02-11', '2011-02-12', '2011-02-13',
       '2011-02-14', '2011-02-15', '2011-02-16', '2011-02-17',
       '2011-02-18', '2011-02-19', '2011-02-20', '2011-02-21',
       '2011-02-22', '2011-02-23', '2011-02-24', '2011-02-25',
       '2011-02-26', '2011-02-27', '2011-02-28', '2011-03-01',
       '2011-03-02', '2011-03-03', '2011-03-04', '2011-

In [18]:
bikes.season.unique()

array([1, 2, 3, 4], dtype=int64)

In [19]:
bikes.yr.unique()

array([0, 1], dtype=int64)

In [20]:
bikes["mnth"].uniqueque()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [21]:
bikes.hr.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [22]:
bikes.holiday.unique()

array([0, 1], dtype=int64)

In [23]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [26]:
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [27]:
bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [28]:
bikes.instant.isnull().sum()

0

In [29]:
bikes.instant.duplicated().sum()

0

In [30]:
bikes.dteday.duplicated().sum()

16648

In [31]:
bikes = bikes.dropna()

In [32]:
bikes

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81     0.0000       3   
1               0           1  0.22  0.2727  0.80     0.0000       8   
2               0           1  0.22  0.2727  0.80     0.0000       5   
3               0           1  0.24  0.2879  0.75     0.0000       3   
4               0           1  0.24  0.2879  0.75     0.0000       0   
...           ...         ...   ...     ...   ...        ...     ...   
17374           1           2  0.26  0.2576  0.60     0.1642      11   
17375           1           2  0.26  0.2576  0.60     0.1642       8   
17376           1           1  0.26  0.2576  0.60     0.1642       7   
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
0              13   16  
1              32   40  
2              27   32  
3              10   13  
4               1    1  
...           ...  ...  
17374         108  119  
17375          81   89  
17376          83   90  
17377          48   61  
17378          37   49  

[17379 rows x 17 columns]

In [34]:
bikes.dropna(inplace=True)

In [35]:
bikes.drop_duplicates(subset="instant", inplace=True)

In [37]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [38]:
dte = pd.to_datetime(bikes.dteday)

In [39]:
type(dte)

pandas.core.series.Series

In [40]:
dte.dt.year

0        2011
1        2011
2        2011
3        2011
4        2011
         ... 
17374    2012
17375    2012
17376    2012
17377    2012
17378    2012
Name: dteday, Length: 17379, dtype: int64

In [41]:
dte.dt.month

0         1
1         1
2         1
3         1
4         1
         ..
17374    12
17375    12
17376    12
17377    12
17378    12
Name: dteday, Length: 17379, dtype: int64

In [42]:
dte.dt.day

0         1
1         1
2         1
3         1
4         1
         ..
17374    31
17375    31
17376    31
17377    31
17378    31
Name: dteday, Length: 17379, dtype: int64

In [43]:
dte.dt.weekday

0        5
1        5
2        5
3        5
4        5
        ..
17374    0
17375    0
17376    0
17377    0
17378    0
Name: dteday, Length: 17379, dtype: int64

In [44]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [45]:
bikes.head(2)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40

In [47]:
year = dte.dt.year

In [48]:
type(year)

pandas.core.series.Series

In [49]:
bikes["year_myown"] = year

In [50]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'year_myown'],
      dtype='object')

In [51]:
bikes = bikes.drop("instant", axis =1)

In [52]:
bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'year_myown'],
      dtype='object')

In [53]:
bikes.head(2)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1   0        0        6           0           1   
1  2011-01-01       1   0     1   1        0        6           0           1   

   temp   atemp   hum  windspeed  casual  registered  cnt  year_myown  
0  0.24  0.2879  0.81        0.0       3          13   16        2011  
1  0.22  0.2727  0.80        0.0       8          32   40        2011

<b> Grouping and Merging </b>

In [54]:
bikes.head(3)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1   0        0        6           0           1   
1  2011-01-01       1   0     1   1        0        6           0           1   
2  2011-01-01       1   0     1   2        0        6           0           1   

   temp   atemp   hum  windspeed  casual  registered  cnt  year_myown  
0  0.24  0.2879  0.81        0.0       3          13   16        2011  
1  0.22  0.2727  0.80        0.0       8          32   40        2011  
2  0.22  0.2727  0.80        0.0       5          27   32        2011

In [55]:
bikes_2011 = bikes[ year == 2011 ]

In [56]:
bikes_2011

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0     2011-01-01       1   0     1   0        0        6           0   
1     2011-01-01       1   0     1   1        0        6           0   
2     2011-01-01       1   0     1   2        0        6           0   
3     2011-01-01       1   0     1   3        0        6           0   
4     2011-01-01       1   0     1   4        0        6           0   
...          ...     ...  ..   ...  ..      ...      ...         ...   
8640  2011-12-31       1   0    12  19        0        6           0   
8641  2011-12-31       1   0    12  20        0        6           0   
8642  2011-12-31       1   0    12  21        0        6           0   
8643  2011-12-31       1   0    12  22        0        6           0   
8644  2011-12-31       1   0    12  23        0        6           0   

      weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  \
0              1  0.24  0.2879  0.81     0.0000       3          13   16   
1              1  0.22  0.2727  0.80     0.0000       8          32   40   
2              1  0.22  0.2727  0.80     0.0000       5          27   32   
3              1  0.24  0.2879  0.75     0.0000       3          10   13   
4              1  0.24  0.2879  0.75     0.0000       0           1    1   
...          ...   ...     ...   ...        ...     ...         ...  ...   
8640           1  0.42  0.4242  0.54     0.2239      19          73   92   
8641           1  0.42  0.4242  0.54     0.2239       8          63   71   
8642           1  0.40  0.4091  0.58     0.1940       2          50   52   
8643           1  0.38  0.3939  0.62     0.1343       2          36   38   
8644           1  0.36  0.3788  0.66     0.0000       4          27   31   

      year_myown  
0           2011  
1           2011  
2           2011  
3           2011  
4           2011  
...          ...  
8640        2011  
8641        2011  
8642        2011  
8643        2011  
8644        2011  

[8645 rows x 17 columns]

In [57]:
bikes_2011 = bikes[bikes.yr == 0]

In [58]:
bikes_2011

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0     2011-01-01       1   0     1   0        0        6           0   
1     2011-01-01       1   0     1   1        0        6           0   
2     2011-01-01       1   0     1   2        0        6           0   
3     2011-01-01       1   0     1   3        0        6           0   
4     2011-01-01       1   0     1   4        0        6           0   
...          ...     ...  ..   ...  ..      ...      ...         ...   
8640  2011-12-31       1   0    12  19        0        6           0   
8641  2011-12-31       1   0    12  20        0        6           0   
8642  2011-12-31       1   0    12  21        0        6           0   
8643  2011-12-31       1   0    12  22        0        6           0   
8644  2011-12-31       1   0    12  23        0        6           0   

      weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  \
0              1  0.24  0.2879  0.81     0.0000       3          13   16   
1              1  0.22  0.2727  0.80     0.0000       8          32   40   
2              1  0.22  0.2727  0.80     0.0000       5          27   32   
3              1  0.24  0.2879  0.75     0.0000       3          10   13   
4              1  0.24  0.2879  0.75     0.0000       0           1    1   
...          ...   ...     ...   ...        ...     ...         ...  ...   
8640           1  0.42  0.4242  0.54     0.2239      19          73   92   
8641           1  0.42  0.4242  0.54     0.2239       8          63   71   
8642           1  0.40  0.4091  0.58     0.1940       2          50   52   
8643           1  0.38  0.3939  0.62     0.1343       2          36   38   
8644           1  0.36  0.3788  0.66     0.0000       4          27   31   

      year_myown  
0           2011  
1           2011  
2           2011  
3           2011  
4           2011  
...          ...  
8640        2011  
8641        2011  
8642        2011  
8643        2011  
8644        2011  

[8645 rows x 17 columns]

In [59]:
#sum of casual users grouped by season 

df_by_seasons = bikes.groupby("season")

In [60]:
df_by_seasons

In [61]:
type(df_by_seasons)

pandas.core.groupby.generic.DataFrameGroupBy

In [62]:
df_by_seasons.casual.sum()

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [63]:
bikes

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0      2011-01-01       1   0     1   0        0        6           0   
1      2011-01-01       1   0     1   1        0        6           0   
2      2011-01-01       1   0     1   2        0        6           0   
3      2011-01-01       1   0     1   3        0        6           0   
4      2011-01-01       1   0     1   4        0        6           0   
...           ...     ...  ..   ...  ..      ...      ...         ...   
17374  2012-12-31       1   1    12  19        0        1           1   
17375  2012-12-31       1   1    12  20        0        1           1   
17376  2012-12-31       1   1    12  21        0        1           1   
17377  2012-12-31       1   1    12  22        0        1           1   
17378  2012-12-31       1   1    12  23        0        1           1   

       weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  \
0               1  0.24  0.2879  0.81     0.0000       3          13   16   
1               1  0.22  0.2727  0.80     0.0000       8          32   40   
2               1  0.22  0.2727  0.80     0.0000       5          27   32   
3               1  0.24  0.2879  0.75     0.0000       3          10   13   
4               1  0.24  0.2879  0.75     0.0000       0           1    1   
...           ...   ...     ...   ...        ...     ...         ...  ...   
17374           2  0.26  0.2576  0.60     0.1642      11         108  119   
17375           2  0.26  0.2576  0.60     0.1642       8          81   89   
17376           1  0.26  0.2576  0.60     0.1642       7          83   90   
17377           1  0.26  0.2727  0.56     0.1343      13          48   61   
17378           1  0.26  0.2727  0.65     0.1343      12          37   49   

       year_myown  
0            2011  
1            2011  
2            2011  
3            2011  
4            2011  
...           ...  
17374        2012  
17375        2012  
17376        2012  
17377        2012  
17378        2012  

[17379 rows x 17 columns]

In [64]:
df_by_seasons["casual"].sum()

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [65]:
type(df_by_seasons.casual.sum())

pandas.core.series.Series

In [66]:
series_causual = df_by_seasons.casual.sum()

In [67]:
series_causual 

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [69]:
series_registered = df_by_seasons.registered.sum()

In [70]:
series_registered

season
1    410726
2    715067
3    835038
4    711831
Name: registered, dtype: int64

<b> concat </b>


In [71]:
type(series_causual)

pandas.core.series.Series

In [72]:
type(series_registered)

pandas.core.series.Series

In [73]:
frames = [ series_causual, series_registered]

In [78]:
df = pd.concat(frames,axis=1)

In [79]:
df

casual  registered
season                    
1        60622      410726
2       203522      715067
3       226091      835038
4       129782      711831

In [80]:
df["total"] = df.casual  + df.registered

In [81]:
df

casual  registered    total
season                             
1        60622      410726   471348
2       203522      715067   918589
3       226091      835038  1061129
4       129782      711831   841613

In [82]:
series_causual

season
1     60622
2    203522
3    226091
4    129782
Name: casual, dtype: int64

In [83]:
series_registered

season
1    410726
2    715067
3    835038
4    711831
Name: registered, dtype: int64

In [84]:
df

casual  registered    total
season                             
1        60622      410726   471348
2       203522      715067   918589
3       226091      835038  1061129
4       129782      711831   841613

In [85]:
df["total"]

season
1     471348
2     918589
3    1061129
4     841613
Name: total, dtype: int64

In [86]:
df

casual  registered    total
season                             
1        60622      410726   471348
2       203522      715067   918589
3       226091      835038  1061129
4       129782      711831   841613

In [87]:
df.to_csv("outcome.csv")

In [88]:
type(df)

pandas.core.frame.DataFrame