<b> NumPy (Numeric Python) </b>

<b> Python Array </b>

In [1]:
import array
my_array = array.array('i',[1,2,3,4])

In [2]:
my_array

array('i', [1, 2, 3, 4])

In [3]:
type(my_array)

array.array

In [4]:
my_array = array.array('f',[1.2,2.5,3.2,4.0])

In [5]:
my_array

array('f', [1.2000000476837158, 2.5, 3.200000047683716, 4.0])

<b> NumPy Array </b>

In [6]:
import numpy as np 

In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr = np.array((1,2,3))

In [11]:
arr

array([1, 2, 3])

In [12]:
type(arr)

numpy.ndarray

In [13]:
# Zero dimensional array 
zero_arr = np.array(50)

In [14]:
zero_arr

array(50)

In [15]:
type(zero_arr)

numpy.ndarray

In [16]:
#one dimensional array 
one_arr = np.array([1,2,3,4])

In [17]:
one_arr


array([1, 2, 3, 4])

In [18]:
type(one_arr)

numpy.ndarray

In [19]:
#2D array 
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr)

[[1 2 3]
 [4 5 6]]


In [20]:
float_list = [1.2,1.3,2.4,5.6]
my_np_float_array = np.array(float_list)
my_np_float_array

array([1.2, 1.3, 2.4, 5.6])

In [21]:
type(my_np_float_array)

numpy.ndarray

In [22]:
mixed_element_list = [1,1.2,2,2.5,7]
my_mixed_array = np.array(mixed_element_list)
my_mixed_array

array([1. , 1.2, 2. , 2.5, 7. ])

In [23]:
mixed_element_list = [1,1.2,2,2.5,7,'a','s']
my_mixed_Array = np.array(mixed_element_list)

In [24]:
my_mixed_Array

array(['1', '1.2', '2', '2.5', '7', 'a', 's'], dtype='<U32')

In [27]:
int_list = [1,3,4,8,5]
my_np_array = np.array(int_list, dtype=int)
my_np_array

array([1, 3, 4, 8, 5])

In [28]:
to_back_list = my_np_array.tolist()

In [29]:
to_back_list

[1, 3, 4, 8, 5]

In [30]:
type(to_back_list)

list

<b> Properties of NumPy array </b> 

In [31]:
my_np_array

array([1, 3, 4, 8, 5])

In [32]:
type(my_np_array)

numpy.ndarray

In [33]:
my_np_array.dtype

dtype('int32')

In [34]:
my_np_float_array.dtype

dtype('float64')

In [35]:
my_np_array.ndim

1

In [36]:
my_np_array.shape

(5,)

In [37]:
my_np_array.size

5

<b> Prepopulated arrays </b>

In [38]:
zeros = np.zeros(6)

In [39]:
zeros

array([0., 0., 0., 0., 0., 0.])

In [40]:
zeros.dtype

dtype('float64')

In [42]:
zeros_ints = np.zeros(5,int)
zeros_ints

array([0, 0, 0, 0, 0])

In [43]:
ones = np.ones(3)

In [44]:
ones

array([1., 1., 1.])

In [45]:
np.empty(10)

array([            nan, 0.00000000e+000, 1.55129151e-311, 2.02369289e-320,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [46]:
arange_array = np.arange(1,10)

In [47]:
arange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1 = np.arange(5,50,5)

In [49]:
a1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

<b> 2D Array </b> 

In [174]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

two_d_array = np.array([l1,l2,l3])
two_d_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
l1 = [1,2,3]
l2 = [4,5,9]
a2 = np.array([l1,l2])

In [56]:
a2

array([[1, 2, 3],
       [4, 5, 9]])

In [57]:
two_d_array.dtype

dtype('int32')

In [58]:
two_d_array.ndim

2

In [59]:
two_d_array.size

9

In [60]:
two_d_array.shape

(3, 3)

<b> NumPy Computation </b> 

In [64]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
l1

[1, 2, 3, 4, 5]

In [65]:
a1

array([1, 2, 3, 4, 5])

In [66]:
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)

In [67]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> Ways to access the array elements </b>

In [68]:
a1

array([1, 2, 3, 4, 5])

In [69]:
a1[0]

1

In [70]:
a1[2]

3

In [71]:
a1[-1]

5

In [72]:
a1

array([1, 2, 3, 4, 5])

In [73]:
a1[3] = 4444
a1

array([   1,    2,    3, 4444,    5])

In [74]:
a1[:]

array([   1,    2,    3, 4444,    5])

In [75]:
a1[:2]

array([1, 2])

In [76]:
a1[3:]

array([4444,    5])

In [77]:
a1[1:3]

array([2, 3])

In [78]:
a1[-2:-4]

array([], dtype=int32)

In [79]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
a2[0][0]

1

In [81]:
a2[1][2]

6

In [82]:
a2[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a2[0,0]

1

In [84]:
a1

array([   1,    2,    3, 4444,    5])

In [85]:
a_sub = a1[:3]
a_sub

array([1, 2, 3])

In [86]:
a_sub[0] = 35

In [87]:
a_sub

array([35,  2,  3])

In [88]:
a1

array([  35,    2,    3, 4444,    5])

In [89]:
a_sub_view = a1.view()

In [90]:
a_sub_view

array([  35,    2,    3, 4444,    5])

In [91]:
a1[0] = 100 

In [92]:
a1

array([ 100,    2,    3, 4444,    5])

In [93]:
a_sub_view

array([ 100,    2,    3, 4444,    5])

In [94]:
a_copy = a1.copy()

In [95]:
a_copy


array([ 100,    2,    3, 4444,    5])

In [96]:
a_copy[0] = 200

In [97]:
a_copy

array([ 200,    2,    3, 4444,    5])

In [98]:
a1

array([ 100,    2,    3, 4444,    5])

<b> Reshaping <b> 

In [99]:
a1
print("a1 ===> " , a1)
print(a1.shape)
print(a1.ndim)

a1 ===>  [ 100    2    3 4444    5]
(5,)
1


In [100]:
a1_reshaped = a1.reshape(5,1)
print("a1_shaped ==> ", a1_reshaped)
print("\n", a1_reshaped.shape)
print("\n", a1_reshaped.ndim)

a1_shaped ==>  [[ 100]
 [   2]
 [   3]
 [4444]
 [   5]]

 (5, 1)

 2


In [101]:
a1

array([ 100,    2,    3, 4444,    5])

In [102]:
one_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [105]:
two_Arr = one_arr.reshape(3,4)

In [106]:
two_Arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<b> Computation - Arit <b> 

In [107]:
a1

array([ 100,    2,    3, 4444,    5])

In [109]:
sum(a1)

4554

In [110]:
a11 = np.random.randint(1,100,size=1000)
a11.size

1000

In [111]:
a11

array([61, 36, 62, 23, 16, 29, 96, 17, 78, 46, 85, 56, 67, 28, 12, 29, 74,
       91, 47, 91, 62, 44, 93, 11, 26, 33, 21, 26, 10,  3, 58, 69, 27, 35,
       13, 35, 72, 65, 36, 44, 79, 13, 85, 54, 18, 90, 90, 44, 49, 79, 99,
       94, 86, 55, 78, 46, 87, 76, 56, 18, 57, 74, 32, 81, 79, 96, 28, 29,
       83, 55, 48, 30, 69, 27,  8, 37, 79, 88, 93,  9, 12, 46, 49,  6,  1,
       52, 38, 74, 61,  2, 19, 27, 90, 97, 87, 65, 38, 36, 57, 55, 42, 11,
       69,  3, 75,  6, 42,  7, 61, 15, 77, 19, 97, 86, 62, 62, 64, 26, 53,
       19, 17, 88, 55,  3, 71,  4, 45, 40,  4, 59,  9, 34,  7,  6, 45, 13,
       55, 96,  6, 35, 60, 83, 37,  8, 88, 13, 99, 46, 46,  8, 20, 12, 48,
       38, 16, 39, 31, 57, 56, 74, 64, 65, 83, 15, 74, 37, 12, 30, 31, 45,
       40, 61, 36, 79, 25, 85, 59, 59,  3, 22, 53, 66, 59, 80, 72, 53, 68,
       97, 47,  4, 65, 74, 68, 46, 15, 45,  9, 27, 85, 61, 80, 60, 45, 28,
       45, 77, 67, 56, 11, 78, 83, 67, 25, 31, 59, 72, 67, 59, 63, 48, 16,
       81,  2,  5, 37, 36

In [112]:
sum(a11)

49816

In [113]:
np.sum(a11)

49816

In [114]:
%timeit sum(a11)

180 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [115]:
%timeit np.sum(a11)

4.85 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
a1

array([ 100,    2,    3, 4444,    5])

In [117]:
a1 + 5 

array([ 105,    7,    8, 4449,   10])

In [118]:
a1 ** 2

array([   10000,        4,        9, 19749136,       25], dtype=int32)

In [119]:
np.add(a1,5)

array([ 105,    7,    8, 4449,   10])

In [120]:
np.power(a1,2)

array([   10000,        4,        9, 19749136,       25], dtype=int32)

In [121]:

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
a2 + 3 

array([[4, 5, 6],
       [7, 8, 9]])

In [123]:
a2 - 5

array([[-4, -3, -2],
       [-1,  0,  1]])

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.sum(a2,axis=0)

array([5, 7, 9])

In [127]:
np.sum(a2,axis=1)

array([ 6, 15])

<b> Comparisons </b>

In [128]:
a1

array([ 100,    2,    3, 4444,    5])

In [129]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
type(a2)

numpy.ndarray

In [131]:
a1 

array([ 100,    2,    3, 4444,    5])

In [132]:
a1 == 5

array([False, False, False, False,  True])

In [133]:
a1 != 45

array([ True,  True,  True,  True,  True])

In [135]:
a1

array([ 100,    2,    3, 4444,    5])

In [137]:
(a1 < 500)

array([ True,  True,  True, False,  True])

In [138]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.sum(a2 < 100)

6

In [140]:
(a2 < 100)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [145]:
#np.greater(a1,5)

a1 > 5 

array([ True, False, False,  True, False])

In [142]:
# Aggregations 

a1

array([ 100,    2,    3, 4444,    5])

In [143]:
a1.sum()

4554

In [144]:
np.sum(a1)

4554

In [146]:
a1.max()

4444

In [147]:
a1.min()

2

In [148]:

a1.mean()

910.8

In [150]:
a1.std()


1766.9969326515538

In [151]:
a1.var()

3122278.1599999997

In [152]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
a2.min()

1

In [154]:
a2.max()

6

In [155]:
np.sum(a2,axis=0)

array([5, 7, 9])

In [156]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
np.min(a2,axis=1)

array([1, 4])

In [158]:
np.any(a1>5)

True

In [161]:
np.any((a1>5) | (a1 < 10))

True

In [162]:
a1

array([ 100,    2,    3, 4444,    5])

In [163]:
a1

array([ 100,    2,    3, 4444,    5])

In [164]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> Linear Algebra </b>

In [166]:
X = np.array([[1,2],[3,4]])
print(X)


[[1 2]
 [3 4]]


In [167]:
X.transpose()

array([[1, 3],
       [2, 4]])

In [168]:
x = np.eye(3)

In [169]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
#Fruit seller .... Wed : 20 mangoes and 10oranges ... Rs 350 

# Thursday 17 mangoes and 22 oranges ..... Rs. 500 

# both days price of the fruits dint change , what is the price of each fruits ? 

In [171]:
# x --> mangoes 
# y --> orange 

#20x + 10y = 350 
#17x + 22y = 500 

In [173]:
A = np.array([[20,10],[17,22]])
B = np.array([350,500])
X = np.linalg.solve(A,B)
print(X)

[10. 15.]
